### ISSUE TITLE
Egg Dropping Puzzle

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#107]
**This issue is up for Python implementation.**

Egg dropping refers to a class of problems in which it is important to find the correct response without exceeding a (low) number of certain failure states. 

**Is your feature request related to a problem? Please describe.**
In a toy example, there is a tower of n floors and an egg dropper with m ideal eggs. The physical properties of the ideal egg are such that it will shatter if it is dropped from floor n^*n or above, and will have no damage whatsoever if it is dropped from floor n^*-1n or below. The problem is to find a strategy such that the egg dropper can determine the floor n^*n in as few eggs drop as possible. 

**Describe the solution you'd like**
This problem has many applications in the real world such as avoiding a call out to the slow HDD or attempting to minimize cache misses or running a large number of expensive queries on a database.

**Additional context**
Content is taken from https://brilliant.org/wiki/egg-dropping/

**Languages**
- [x] Python
- [x] Java
- [ ] C
- [x] C++

**Comment by codewdhruv** [comment]
I would like to contribute in this with C++ @kaustubhgupta @YashSaxena9

**Comment by kaustubhgupta** [comment]
@dhrubajyoti89 assigned

**Comment by ashish-garg18** [comment]
I would like to work on this using c. Can you assign me this.

**Comment by kaustubhgupta** [comment]
@ashish-garg18 assigned

**Comment by theDeepanshuMourya** [comment]
I would like to contribute to this problem using Java language @kaustubhgupta @YashSaxena9

**Comment by kaustubhgupta** [comment]
@theDeepanshuMourya assigned

**Comment by codewdhruv** [comment]
@kaustubhgupta  Check this action fails for fork/PR model #165

**Comment by kaustubhgupta** [comment]
@ashish-garg18 will you make PR in C?

**Comment by kaustubhgupta** [comment]
This issue is up for Python and C implementation.

**Comment by Obnoxious-coder** [comment]
I would like to contribute to this problem using C  language @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@Obnoxious-coder assigned to you in C

**Comment by kaustubhgupta** [comment]
@Obnoxious-coder are you working on this?

**Comment by SaurabhVj** [comment]
I would like to implement this in C @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@SaurabhVj assigned to you. Make sure to follow contribution guidelines

**Comment by Obnoxious-coder** [comment]
@kaustubhgupta I was working on the c solution, can u assign it back

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I was working on the c solution, can u assign it back

@SaurabhVj is new here and I think we should allow him to make his first contribution. @Obnoxious-coder can you take another issue now?

**Comment by SaurabhVj** [comment]
Thank You @kaustubhgupta . I have made a pull request with the code solving the puzzle. Please look into it.
