### ISSUE TITLE
Updating readme of all languages

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#108]
For every language folder, we need a readme file.

**Is your feature request related to a problem? Please describe.**
It is becoming difficult to track codes which are merged or nor

**Describe the solution you'd like**
Update the readme describing language in one-line following by a table with columns of name, algorithm/program added.

**Additional context**
This needs to be done on an urgent basis

**Languages**
- [x] Markdown

**Comment by YashSaxena9** [comment]
I'll be doing it! :)
