### ISSUE TITLE
Refactory code base

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#11]
# Description
Currently, the codes are not in there designated folders. All the codes are in the master branch.

# Solution I want
Make separate folders for each language and create a readme to explain the language in one line. Folders I want:
- Python
- Java
- C
- C++
- HTML
- Others (here only create the readme without any description)

**Comment by adityathakurxd** [comment]
Can you assign me this issue?

**Comment by kaustubhgupta** [comment]
@adityathakurxd assigned to you
