### ISSUE TITLE
Add contribution guidelines  

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#12]
# Description 
Currently, the project has no specific contribution guidelines. Add the contribution.md file in the master and link it in the readme section of the repository.

**Comment by Quest-360** [comment]
ah i didnt get it, can u please elaborate :)

**Comment by kaustubhgupta** [comment]
Something similar to this,
https://github.com/HarshCasper/Rotten-Scripts/blob/master/CONTRIBUTING.md
You can take your own screenshots and but don't plagiarize the whole content

**Comment by adeleke5140** [comment]
hello, I'd like to work on this issue

**Comment by adeleke5140** [comment]
I just made a PR for this issue. would be glad if you checked it out
