### ISSUE TITLE
Explore YouTube Trending Videos

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#124]
Here you will explore the trending section of the YouTube section of your country

**Is your feature request related to a problem? Please describe.**
Not exactly, but this list can be starters for Data Analysis and further merged as a Data Extraction method.

**Describe the solution you'd like**
Come up with a script that stores the title of the video, youtube channel name, number of likes, dislikes, views, no of comments, date of publishing, description of the video (if possible) in a CSV file. Make sure to create a separate folder for this and include code file and CSV too.

**Additional context**
You can make use of the official Google API for this purpose or create your own script from scratch.

**Languages**
- [x] Python
- [ ] Java
- [ ] C
- [ ] C++

**Comment by aditsawant** [comment]
I'd love to work on it with Python. Can you assign it to me?

**Comment by kaustubhgupta** [comment]
@aditsawant okay assigned to you! Make sure to look at the pinned issue "Important Announcements to check guidelines"

**Comment by kaustubhgupta** [comment]
@aditsawant  are you working on this?

**Comment by Obnoxious-coder** [comment]
@kaustubhgupta  can u assign it to me ,if no ones working on this

**Comment by kaustubhgupta** [comment]
If @aditsawant doesn't make PR in two days then I will assign this to you (@Obnoxious-coder )

**Comment by aditsawant** [comment]
Hey @kaustubhgupta, I have made a PR right now.
The code can extract the video's title, views, likes, and dislikes.
Maybe you can merge my PR and let @Obnoxious-coder add the functionality for getting the video description. It's up to you though :)
