### ISSUE TITLE
I want to add a calculator with more than just basic functions using C language

### ISSUE THREAD

**Issue by manish2202** [kaustubhgupta/Hacktoberfest#125]
Please include a small description or summary of the issue here.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Languages**
- [ ] Python
- [ ] Java
- [x] C
- [ ] C++

I will be adding a calculator with sqrt, log, power func along with basic operations using C language
[c calculator for github.txt](https://github.com/kaustubhgupta/Hacktoberfest2020_/files/5319449/c.calculator.for.github.txt)

**Comment by manish2202** [comment]
It will be more than just basic addition, subtraction, multiplication, division.

**Comment by kaustubhgupta** [comment]
@manish2202 will this be a GUI application or menu-driven program?

**Comment by manish2202** [comment]
menu-driven.

**Comment by kaustubhgupta** [comment]
@manish2202 okay go ahead, make sure to create a separate branch in your forked repo. Also, add a screenshot of the menu which will be displayed in the output, and put both files in one folder

**Comment by manish2202** [comment]
sure

**Comment by b-samarth** [comment]
can I do the same using java?

**Comment by kaustubhgupta** [comment]
@b-samarth okay go ahead and follow the same instruction given to this participant 

> @manish2202 okay go ahead, make sure to create a separate branch in your forked repo. Also, add a screenshot of the menu which will be displayed in the output, and put both files in one folder

**Comment by kaustubhgupta** [comment]
@manish2202 WIll you make new PR ?

**Comment by shreya-bera** [comment]
If still open I can do it in C

**Comment by ishanbagchi** [comment]
Can I add a scientific calculator using Python and Tkinter, or should I add a menu-driven one?

**Comment by kaustubhgupta** [comment]
@shreya-bera I am waiting for @manish2202 reply. If he fails to reply within 24 hrs then I will assign this issue in C to you

**Comment by kaustubhgupta** [comment]
@ishanbagchi assigned to you in Python. Make sure to look at the pinned issues to avoid PR rejection

**Comment by manish2202** [comment]
> @manish2202 WIll you make new PR ?

yes I can make one. My last PR got marked as invalid.

**Comment by manish2202** [comment]
May I know why was my PR marked invalid?

**Comment by kaustubhgupta** [comment]
> May I know why was my PR marked invalid?

I have commented the reason on the PR when it was closed

**Comment by shreya-bera** [comment]
> @shreya-bera I am waiting for @manish2202 reply. If he fails to reply within 24 hrs then I will assign this issue in C to you

Its around 24 hours, can you reassign the calculator in c task to me.

**Comment by kaustubhgupta** [comment]
> > @shreya-bera I am waiting for @manish2202 reply. If he fails to reply within 24 hrs then I will assign this issue in C to you
> 
> Its around 24 hours, can you reassign the calculator in c task to me.

He has replied the very next hour and made a PR (though it was invalid again) If he makes another one with new instructions then it's fine but if it happens again then I will assign this issue directly to you!

**Comment by kaustubhgupta** [comment]
This issue is up for C++

**Comment by Mayank-11** [comment]
I reccomend to use python

**Comment by kaustubhgupta** [comment]
@shreya-bera do you want to do this in C?

**Comment by kaustubhgupta** [comment]
@Mayank-11 The PR for the same has been made by another person

**Comment by shreya-bera** [comment]
> @shreya-bera do you want to do this in C?

Yes, if its open I can do it.

**Comment by kaustubhgupta** [comment]
@shreya-bera assigned to you in C

**Comment by adilsp5075** [comment]
i want to work on this issue
I have done an HTML code also for this particular issue

**Comment by kaustubhgupta** [comment]
@adilsp5075 only C language implementation is left. So do you want to contribute to this? And original code not published on other repo as recently I have marked two PRs as plagiarised because the same code was pushed on different hacktoberfest repos.

**Comment by adilsp5075** [comment]
I would like to contribute my own code
It has a basic four functions and extra two functions (power and factor of
numbers)

**Comment by kaustubhgupta** [comment]
@adilsp5075 okay, make it menu-driven, attach the screenshot, and put both the files in one folder. Update the language readme too

**Comment by adilsp5075** [comment]
Thank you
Let me try this 😊
