### ISSUE TITLE
I want to add a chatbot made with python 

### ISSUE THREAD

**Issue by rijusougata13** [kaustubhgupta/Hacktoberfest#127]
Please include a small description or summary of the issue here.
**project**
chat bot using sentiment analysis
**Is your feature request related to a problem? Please describe.**
this will not solve a real life problem but it can be use as a part of a big problem
**Describe the solution you'd like**
i am using sentiment analysis to extract information what user input ..dividing them in 3 categories like pos,neg,nutral..there is 3 different list for each..anyone can add there ans to them.and my script will randomly choose a sentence and display .

**Additional context**
this is command line based..but it can be deployed as web app using flask .

**Languages**
- [x] Python
- [ ] Java
- [ ] C
- [ ] C++

**Comment by kaustubhgupta** [comment]
@rijusougata13 Please fill the template properly, only the title can't give me enough information about what this chat will do, various functions, and will it be GUI or command-line utility. Edit the template and then if it is good enough I will assign this issue

**Comment by rijusougata13** [comment]
@kaustubhgupta  i updated the template can you assign me into this now?

**Comment by kaustubhgupta** [comment]
@rijusougata13 sounds interesting, you can start your work. Make sure to create a separate branch for this, add a GIF to show how the program is working, and put all these files in a separate folder under the Python directory.
