### ISSUE TITLE
Improve README.md of the Repo

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#13]
# Description
You must have seen the readme file. It is not very attractive. Add some details about hacktoberfest, add language badges, and so on depends on your creativity. You can take inspiration from various other repositories that are part of this program!

**Comment by AnirudhPanda** [comment]
I would like to work on this @kaustubhgupta

**Comment by AnirudhPanda** [comment]
#25 Done! Please check it.
