### ISSUE TITLE
I want to add Graph Algorithms

### ISSUE THREAD

**Issue by theDeepanshuMourya** [kaustubhgupta/Hacktoberfest#133]
I would like to add Graph traversal algorithms which include Breadth-First Search (BFS) & Depth First Search (DFS), Cycle Detection Algorithm as well as Shortest Path Detection Algorithms which include Dijkstra Algorithm & Bellman-Ford Algorithm.

**Is your feature request related to a problem? Please describe.**
Yes, all these algorithms are related to basic graph problems.

**Describe the solution you'd like**
These algorithms have many applications which are as follows.
1. Computer games - finding the best/shortest route from one point to another.
2. Maps - finding the shortest/cheapest path for a car from one city to another, by using given roads.
3. May be used to find the fastest way for a car to get from one point to another inside a certain city. E.g. satellite navigation system that shows to drivers which way they should better go.

**Additional context**
Content is taken from my own repository [DataStructuresAndAlgorithms](https://github.com/theDeepanshuMourya/DataStructuresAndAlgorithms)

**Languages**
- [ ] Python
- [x] Java
- [ ] C
- [ ] C++

**Comment by YashSaxena9** [comment]
@theDeepanshuMourya go for it, issue assigned to you for language **Java**.
Please follow our contribution guide to avoid rejection of PR, happy coding! :D

**Comment by ng29** [comment]
Hey, i can take for cpp, please assign it to me

**Comment by kaustubhgupta** [comment]
@ng29 Assigned to you in C++

**Comment by kaustubhgupta** [comment]
@ng29 we already have BFS and DFS in C++ so which algo you will contribute to?

**Comment by kaustubhgupta** [comment]
@theDeepanshuMourya Are you working on this? If yes then specify which algo and make sure to check the java directory to avoid any clashing algo!

**Comment by ng29** [comment]
> @ng29 we already have BFS and DFS in C++ so which algo you will contribute to?

Ahh, i think i missed ya..
Toplogical sort is not there, right?  I can submit that

**Comment by kaustubhgupta** [comment]
@ng29 okay assigned to you! Please follow our contribution guide to avoid rejection of PR, happy coding! :D

**Comment by theDeepanshuMourya** [comment]
@kaustubhgupta Yes, I'm working on it. I'll check the java directory before pushing a PR.

**Comment by aditsawant** [comment]
Do you need only Java implementations or C++ ones would work too?
Asking because all the code in the main repo is in Java.
