### ISSUE TITLE
I want to add more Linked List algorithims in C

### ISSUE THREAD

**Issue by thisisrick25** [kaustubhgupta/Hacktoberfest#142]
I want to add more Linked List algorithms in C

**Is your feature request related to a problem? Please describe.**
These are basic Linked List algos

**Describe the solution you'd like**
I'll be adding the solutions

**Additional context**
From my GitHub [thisisrick25](https://github.com/thisisrick25/data-structures-and-algorithim)

**Languages**

-   [ ] Python
-   [ ] Java
-   [x] C
-   [ ] C++

**Comment by IamBikramPurkait** [comment]
I would like to contribute in this python

**Comment by kaustubhgupta** [comment]
@thisisrick25 assigned to you
