### ISSUE TITLE
I would like to contribute in python. I want make a multiplication table.

### ISSUE THREAD

**Issue by IamBikramPurkait** [kaustubhgupta/Hacktoberfest#147]
**Is your feature request related to a problem? Please describe.**
I want to make a simple multiplication table using python.

**Describe the solution you'd like**
It asks a user for a number, then it will show the multiplication table of the user input number.

**Languages**

-   [x] Python

**Comment by kaustubhgupta** [comment]
can you make this a GUI application otherwise it's way too naive
