### ISSUE TITLE
I want to add floyd's cycle detection algorithm for linked list

### ISSUE THREAD

**Issue by listout** [kaustubhgupta/Hacktoberfest#149]
I want to add floyd's cycle detection algorithm for linked list.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Implement floyd's cycle detection algorithm using fast and slow pointer.

**Additional context**
[More context from wikipeida](https://en.wikipedia.org/wiki/Cycle_detection#Floyd's_Tortoise_and_Hare)

**Languages**

-   [x] C

**Comment by kaustubhgupta** [comment]
@listout assigned, have a look at pinned issues to avoid PR rejection
