### ISSUE TITLE
Add templates for issues and pull request

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#15]
# Description 
Using GitHub actions, integrate the templates for the pull requests and issue creations. Take inspiration from other repositories but make sure not to plagiarise any content. Make it customized for this repo. You can discuss with me what things I want to consider when you are assigned this issue

**Comment by arps18** [comment]
Hey @kaustubhgupta I would like to work on the issue!

**Comment by kaustubhgupta** [comment]
@arps18 assigned to you!

**Comment by aaishikasb** [comment]
Can you assign me the issue? Would like to work on it!

**Comment by kaustubhgupta** [comment]
Okay assigned to you @aaishikasb

**Comment by aaishikasb** [comment]
On it!

**Comment by aaishikasb** [comment]
#40 
Added a PR please check.

**Comment by aaishikasb** [comment]
#44 
Please approve, added the requested changes.
