### ISSUE TITLE
I want to add path visualization program using BFS and DFS

### ISSUE THREAD

**Issue by listout** [kaustubhgupta/Hacktoberfest#151]
I want to add path visualization program using bfs and dfs

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make  a path visualization program in python using pygame for the BFS and DFS algorithms

**Additional context**
The user will have the ability to make start and end point and create walls. Once done an key must be pressed for the program to start and will visualize the path from start to end point and then will color the best route according to the algorithm.

**Gif**

![gif](https://github.com/listout/python_pathvisualizer/blob/master/gifs/bfs_gif.gif?raw=true)

**Languages**

-   [x] Python

**Comment by kaustubhgupta** [comment]
@listout if you have already implemented it then we don't require copied code. If you can customize this/improve this here then specify how

**Comment by listout** [comment]
Yes I have implemented this. I got assigned another one so I'll close this one.
