### ISSUE TITLE
Add code of conduct 

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#16]
# Description 

Add a code of conduct to the repository. You can take reference from this https://ubuntu.com/community/code-of-conduct . 
- Don't copy the whole content, add your own creativity and describe the content
- make it error-free
- report your plagiarism score by checking it on any freely available online checker.

**Comment by pritamnegi** [comment]
@kaustubhgupta can I work on this issue?

**Comment by kaustubhgupta** [comment]
@pritamnegi assigned to you! hope you have read the contribution guidelines

**Comment by pritamnegi** [comment]
@kaustubhgupta Yes sure will take a look at that

**Comment by pritamnegi** [comment]
Hi @kaustubhgupta . Can i please get your email id. I need to include it in code of conduct file for reporting if any violation of code of conduct is observed.

**Comment by kaustubhgupta** [comment]
> Hi @kaustubhgupta . Can i please get your email id. I need to include it in code of conduct file for reporting if any violation of code of conduct is observed.

Don't worry about that, just add the line, Contact me (kaustubh) on kaustubhgupta.xyz

**Comment by pritamnegi** [comment]
Ok thanks

**Comment by aaishikasb** [comment]
Is the issue still open? Would love to work on it or assist?

**Comment by kaustubhgupta** [comment]
@aaishikasb this is already assigned to someone else. You can create another issue or wait for new issues!

**Comment by aaishikasb** [comment]
Sure, thanks!
