### ISSUE TITLE
I would like add implementation of Hash table using C

### ISSUE THREAD

**Issue by Sashi445** [kaustubhgupta/Hacktoberfest#170]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implementation of hash tables 

**Languages**
-   C

**Comment by kaustubhgupta** [comment]
@Sashi445 assigned, do have a look at pinned issues to avoid PR rejection

**Comment by Sashi445** [comment]
> @Sashi445 assigned, do have a look at pinned issues to avoid PR rejection

Sure!!
