### ISSUE TITLE
prime checker

### ISSUE THREAD

**Issue by rcs10** [kaustubhgupta/Hacktoberfest#172]
would like to add a java code to check if the entered number is prime or not.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
time complexity = O(sqrt(n))

**Languages**

-   [ ] Python
-   [x] Java
-   [ ] C
-   [ ] C++

**Comment by codewdhruv** [comment]
i would like to contribute with C++

**Comment by kaustubhgupta** [comment]
This is way too naive for this repo, closing this issue

> This stands cancelled

**Comment by codewdhruv** [comment]
@kaustubhgupta this is available for?

**Comment by kaustubhgupta** [comment]
@rcs10 Please have a look at pinned issues to avoid any PR rejection!

@dhrubajyoti89 assigned to you too
