### ISSUE TITLE
readme update

### ISSUE THREAD

**Issue by rcs10** [kaustubhgupta/Hacktoberfest#179]
Please include a small description or summary of the issue here.

issue #172 
Ohh no problem,
plz redefine the "code I expect" accordingly 

**Additional context**
I wonder why u made me raise the issue in the first place if u thought my contribution was too naive

thank you

**Comment by kaustubhgupta** [comment]
Apologies I misunderstood my own words! I have reopened the issue and assigned it to you. Waiting for your PR!
