### ISSUE TITLE
password management app 

### ISSUE THREAD

**Issue by shaalwan** [kaustubhgupta/Hacktoberfest#183]
i wanted to add a python project 
a password management app.
i hoping if could add it here.

**Languages**

-   [x] Python

**Comment by kaustubhgupta** [comment]
@shaalwan The idea is great! So will it be a GUI application?

**Comment by WHITEWOLF619** [comment]
hey, can you assign me this? I can create a password creator/ text generator with special characters which can be used in the application

**Comment by kaustubhgupta** [comment]
@WHITEWOLF619 which language as most probably Python will be taken by @shaalwan

**Comment by WHITEWOLF619** [comment]
yup python i

> @WHITEWOLF619 which language as most probably Python will be taken by @shaalwan

I can work with python.

**Comment by WHITEWOLF619** [comment]
> @WHITEWOLF619 which language as most probably Python will be taken by @shaalwan

sure. I can work with python.

**Comment by shaalwan** [comment]
yes it will be a GUI application. i will be using tkinter module for it.

**Comment by kaustubhgupta** [comment]
@shaalwan go ahead and make sure to have a look at pinned issues to avoid PR rejection!

**Comment by shaalwan** [comment]
thank you!! added my pull request.

**Comment by WHITEWOLF619** [comment]
> yes it will be a GUI application. i will be using tkinter module for it.

I can give the password generation algorithm.
