### ISSUE TITLE
Vigenere cipher using Python

### ISSUE THREAD

**Issue by abhinavkmr569** [kaustubhgupta/Hacktoberfest#191]
Please include a small description or summary of the issue here.

I wanted to ask whether can I publish a code about Vigenere cipher (an encryption method to encrypt alphabets) based on Python

**Comment by kaustubhgupta** [comment]
@abhinavkmr569 Yes sounds interesting! Assigned to you

**Comment by abhinavkmr569** [comment]
Thanks a lot
