### ISSUE TITLE
Urgent: GitHub action to stale PRs

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#192]
GitHub action to put the label of stale on PR after 7 days

**Is your feature request related to a problem? Please describe.**
I am not unable to track PRs which are unattended. 

**Describe the solution you'd like**
Create a GitHub action to stale the PRs which are open for more than 7 days and on the 10th day close them with the label invalid

**Additional context**
I need this action ASAP!

**Languages**

- [x] YAML

**Comment by dynomite567** [comment]
I can take a look into this. I'll let you know once I have something!

**Comment by dynomite567** [comment]
Alright, I found a solution and added it to the workflows directory. You can take a look at the PR I mentioned below. Let me know if you want me to change or edit anything!
