### ISSUE TITLE
i want to add bubble, selection and insertion sort in java.

### ISSUE THREAD

**Issue by manviiguptaa** [kaustubhgupta/Hacktoberfest#197]
Please include a small description or summary of the issue here.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Languages**

-   [ ] Python
-   [ ] Java
-   [ ] C
-   [ ] C++

Bubble Sort in C: @Yatindra29
Insertion Sort in C: @Sneh6020
Bubble, selection, and insertion in Java: @manviiguptaa
Bubble, selection, and insertion in Python: @Kiranmayep

**Comment by manviiguptaa** [comment]
please assign me this

**Comment by kaustubhgupta** [comment]
@manviiguptaa assigned to add these algos in Java
