### ISSUE TITLE
Diffie Hellman Key Exchange Algorithm Using Python

### ISSUE THREAD

**Issue by abhinavkmr569** [kaustubhgupta/Hacktoberfest#198]
Hey, can I post a python code on Diffie Hellman (DH) key exchange algorithm which is a method for securely exchanging cryptographic keys over a public communications channel?

**Comment by abhinavkmr569** [comment]
Or on RSA algorithm?

**Comment by abhinavkmr569** [comment]
Hey, can you assign RSA algorithm to me?

**Comment by kaustubhgupta** [comment]
@abhinavkmr569 are you sure you haven't pushed this code somewhere else?

**Comment by abhinavkmr569** [comment]
yes i haven't posted my RSA code yet

**Comment by kaustubhgupta** [comment]
@abhinavkmr569 okay assigned to you! Make sure to look at the pinned issue "Important Announcements to check guidelines"

**Comment by abhinavkmr569** [comment]
Tbh, I didn't know about that rule and hence after that, I closed my pull request from every repo and then uploaded new file

**Comment by kaustubhgupta** [comment]
> Tbh, I didn't know about that rule and hence after that, I closed my pull request from every repo and then uploaded new file

Good thing!

**Comment by abhinavkmr569** [comment]
Hey, just wanted to know that can I upload a code, that I have already uploaded on other repo, but have closed the pull request for it? I have even unforked that repo. But I forgot to delete that code from that repo, and now I am unable to delete as it says that the branch doesn't exist

**Comment by abhinavkmr569** [comment]
Or can I upload the file here, and then you can check whether or not it still counts as spam?

**Comment by kaustubhgupta** [comment]
I am not sure if that repo admin has marked that PR as invalid or not

**Comment by abhinavkmr569** [comment]
https://github.com/bhaveshlohana/HacktoberFest2020-Contributions/pull/949
This is the link

**Comment by abhinavkmr569** [comment]
Or can you suggest something new?

**Comment by kaustubhgupta** [comment]
Do one thing, I have reviewed the code, and here some changes
- Add comments to explain the functions created and information about algo
- Remove trailing spaces in the end
- When making PR here update the repo language readme.

I think it would work

**Comment by abhinavkmr569** [comment]
Yes, I tried to make those changes and have uploaded the same

**Comment by abhinavkmr569** [comment]
Yes I have made those changes specified
