### ISSUE TITLE
Folder Separator

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#221]
Separates files into the respective folder

**Is your feature request related to a problem? Please describe.**
It is difficult to separate files into different folders

**Describe the solution you'd like**
Separates files into the respective folder

**Additional context**
No

**Languages**

-   [x] Python
-   [ ] Java
-   [ ] C
-   [ ] C++

**Comment by SusnatoPrime007** [comment]
I want to fix typo of the heading.

**Comment by SusnatoPrime007** [comment]
It would be Folder "Separator"

**Comment by shalika10** [comment]
@kaustubhgupta can you elaborate on this issue in detail

**Comment by vivek-alt** [comment]
Hi @kaustubhgupta , I would like to work on this. Could you please assign it to me for Java?
