### ISSUE TITLE
Linear,Binary search Algos 

### ISSUE THREAD

**Issue by shubhamc1200** [kaustubhgupta/Hacktoberfest#222]
Linear, Binary search Algos

# Is your feature request related to a problem? Please describe.
These are basic search algos wherein array is given and we've to find an element's position in the array.

# Describe the solution you'd like
Linear search: Start from the leftmost element of arr[] and one by one compare x with each element of arr[].(A loop is used).Here one doesn't have to sort the array.
Binary Search: Search a sorted array by repeatedly dividing the search interval in half.

# Additional context
TIME COMPLEXITY:
Linear search :O(n)
Binary Search: O(log n)
Jump Search:  O(√n)

Languages:
- [x] Python
- [x] Java
- [x] C
- [x] C++

We will accept Binary and Linear search for this,
@shubhamc1200 Java
@Blackwidow2981 Python
@rai1410swati C
@utkarsh48 C++

**Comment by shubhamc1200** [comment]
please assign me this

**Comment by kaustubhgupta** [comment]
@shubhamc1200 fill this issue template before I assign this issue to you

**Comment by Blackwidow2981** [comment]
Hi,I would like to work on this issue.

**Comment by rai1410swati** [comment]
Hi! I would like to work on this issue as I think it will be a good start for beginners like me in open source contribution.

**Comment by kaustubhgupta** [comment]
@Blackwidow2981 and @rai1410swati Please specify the language and algorithms you would like to contribute

**Comment by rai1410swati** [comment]
I can work on linear and binary search algorithms in java language.

**Comment by Blackwidow2981** [comment]
Hi @kaustubhgupta 
I would like to work on the linear and binary search algorithms.I know the following languages.
-Java(Would prefer coding this algorithm in Java).
-Python
-C
-C++

**Comment by kaustubhgupta** [comment]
We will accept Binary and Linear search for this,
@shubhamc1200 Java
@Blackwidow2981 Python

**Comment by kaustubhgupta** [comment]
@rai1410swati can you work in C or c++ ?

**Comment by rai1410swati** [comment]
Yes @kaustubhgupta I can work in C language

**Comment by kaustubhgupta** [comment]
Okay assigned to you in C

**Comment by shubhamc1200** [comment]
Linear,Binary,Jump search Algos 

**Is your feature request related to a problem? Please describe.**
These are basic search algos wherein array is given and we've to find an element's position in the array.

**Describe the solution you'd like**
 Linear search: Start from the leftmost element of arr[] and one by one compare x with each element of arr[].(A loop is used).Here one doesn't have to sort the array.
Binary Search: Search a sorted array by repeatedly dividing the search interval in half. 
Jump Search: The basic idea is to check fewer elements (than linear search) by jumping ahead by fixed steps or skipping some elements in place of searching all elements.Here the array must be sorted.

**Additional context**
TIME COMPLEXITY:
Linear search :O(n)
Binary Search: O(log n)
Jump Search:
**Languages**

-   [ ] Python
-   [x] Java
-   [ ] C
-   [ ] C++

**Comment by shubhamc1200** [comment]
Okay!

**Comment by shubhamc1200** [comment]
No jump sort?@kaustubh

**Comment by ut-01** [comment]
I would like to contribute in this, in C++.

**Comment by kaustubhgupta** [comment]
@utkarsh48 assigned

**Comment by Blackwidow2981** [comment]
@kaustubhgupta I have added my code as well. Kindly review and merge it .Thank you
