### ISSUE TITLE
I want to add Longest Palindromic Subsequence in Java

### ISSUE THREAD

**Issue by RamneekKaur983** [kaustubhgupta/Hacktoberfest#225]
Implement  "Longest Common Substring" and "Longest Palindromic Subsequence"

Assigned to:

- [X] Java : @RamneekKaur983
- [x] C++ : @chAlekhya

**Comment by YashSaxena9** [comment]
@RamneekKaur983 task assigned to you, please follow the contribution guide.
Hope you'll only submit the optimized (/ DP) version of the problem instead of the brute force method.
Happy coding :)

**Comment by RamneekKaur983** [comment]
I have created the PR request

**Comment by chAlekhya** [comment]
@kaustubhgupta please assign me this for c++.
Thank you :)

**Comment by kaustubhgupta** [comment]
@chAlekhya assigned
