### ISSUE TITLE
I want to add heap sort algorithm in Java and C++

### ISSUE THREAD

**Issue by ghost** [kaustubhgupta/Hacktoberfest#227]
Implement **heap sort** algorithm (for both min and max heap).

**Assigned to:**
-  [X] Java: @AnushkaGarg26
-  [x] C++: @Rahul171201

**Comment by YashSaxena9** [comment]
@AnushkaGarg26 task assigned to you, and please follow our contribution guide.
 happy coding :)

**Comment by ghost** [comment]
@YashSaxena9 Please assign me the C++ part for this issue as well.

**Comment by kaustubhgupta** [comment]
@AnushkaGarg26 we need to give chance to others for contributing to a issue in different language. So if you want to contribute more then look for other issues

**Comment by Rahul171201** [comment]
can I take up this issue? in C++

**Comment by kaustubhgupta** [comment]
@Rahul171201 assigned to you

**Comment by rgarg-2711** [comment]
can you please assign it to me for c++

**Comment by kaustubhgupta** [comment]
@rgarg-2711 This issue was already assigned
