### ISSUE TITLE
I would like to add an android program for creating a simple calculator

### ISSUE THREAD

**Issue by Jainesh18** [kaustubhgupta/Hacktoberfest#245]
Please include a small description or summary of the issue here.

This program will contain the code in java and xml that will demostrate how the simple calculator can be created.

**Is your feature request related to a problem? Please describe.**

No my issue is not related t the ones mentioned but i think it will definetly help one to understand how to build calculator using android.

**Describe the solution you'd like**

As mentioned above my code will simply demostrate how to create a calculator app using android programming.

**Languages**

-   [ ] Java

**Comment by kaustubhgupta** [comment]
I am not sure if we can have this on this repo. @YashSaxena9 what do you think?

**Comment by YashSaxena9** [comment]
@kaustubhgupta I don't think its a good idea to add development based GUI projects not this repo, these mini-projects deserve one of their own repositories.
