### ISSUE TITLE
Anagrams programs 

### ISSUE THREAD

**Issue by PrinceKhatick** [kaustubhgupta/Hacktoberfest#248]
# Making Anagrams programs

Implementation of the String and String Builder class and optimization techniques

Taking two strings as input that are not Anagrams and making them Anagrams by deleting the number of characters required to make them.

Output: An integer denoting the number of characters deleted from both the strings to make them Anagrams.

Languages
-   [x] Python - @chAlekhya
-   [ ] Java - ?
-   [x] C - @Rahul171201

**Comment by kaustubhgupta** [comment]
@PrinceKhatick assigned

**Comment by Rahul171201** [comment]
hi @kaustubhgupta can I take this up in C language?

**Comment by kaustubhgupta** [comment]
@Rahul171201 assigned

**Comment by chAlekhya** [comment]
@kaustubhgupta can I take this up in python?

**Comment by kaustubhgupta** [comment]
@chAlekhya sure! Start coding 😄

**Comment by sadow984** [comment]
@kaustubhgupta can I take this for the c++.
