### ISSUE TITLE
I want to add A* Pathfinding Algorithm with a GUI.

### ISSUE THREAD

**Issue by proghead00** [kaustubhgupta/Hacktoberfest#249]
A* Pathfinding Algorithm with a GUI.

*Implemented with pygame, this script has a GUI, with instructions, and finds the shortest distance between 2 nodes.*

**Additional context**
The GUI is user-friendly and anyone, who isn't in the domain of coding, can play around with it!

**Languages**

-   [x] Python
-   [ ] Java
-   [ ] C
-   [ ] C++

**Comment by kaustubhgupta** [comment]
Your previous PR was marked invalid (the reason is mentioned there) so there is no pointing of assigning this issue to you
