### ISSUE TITLE
I believe there should be a Directory for Hashing Related Problems in the Java Folder

### ISSUE THREAD

**Issue by ATRI2107** [kaustubhgupta/Hacktoberfest#252]
@YashSaxena9 
Hashing related codes include extensive use of HashMap and HashSet Collections of Java. They reduce the time complexity of programs significantly due to the constant time lookup feature. Hashing has always been in the forefront of programming interview questions. I have a bunch of programs and would love to contribute so as to help others.

**Comment by kaustubhgupta** [comment]
@ATRI2107 are you sure you haven't pushed these programs somewhere else because we don't want repeated codes and if found will be marked as spam

**Comment by ATRI2107** [comment]
@kaustubhgupta well those codes are mine only . And as far as hashing is concerned I haven't pushed them to some other repo .

**Comment by kaustubhgupta** [comment]
Which programs you want to contribute? Their names

**Comment by ATRI2107** [comment]
Do check this repository I have maintained. 
I'm attaching the problems I felt they were good enough . 
https://www.github.com/ATRI2107/JAVA-CODES/tree/master/HASHMAP

So if you feel that I can create a PR for the same do let me know

**Comment by kaustubhgupta** [comment]
@ATRI2107 you have already pushed codes to your repository so we don't want to replicate them here. If you have any other problem statement or ideas then create issue for that. For now please close this issue

**Comment by YashSaxena9** [comment]
The codes you wanted to contribute are already available in our repository. You can still contribute if you want to work on any existing issue or create one of your own. :)

**Comment by ATRI2107** [comment]
@YashSaxena9 sure
