### ISSUE TITLE
Guessing Game in C language

### ISSUE THREAD

**Issue by bhavesh1129** [kaustubhgupta/Hacktoberfest#257]
I want to add a small code in the **C language** of **Guessing Game**.

- It is basically a guessing game that allows users to enter any random number within a specific range.

- It also provides some chances to users so that if in case their first guess is wrong they may try one more time.

If you like me to add this code to your repo. Kindly allow me to raise PR.
Thankyou!

**Comment by jackson-roberio** [comment]
I liked the idea and would like to implement the same solution but for java language, should I open a new issue with the same content?

**Comment by kaustubhgupta** [comment]
Assigned to:
@bhavesh1129 C language
@jackson-roberio Java
