### ISSUE TITLE
Count mase path in the chessboard 

### ISSUE THREAD

**Issue by Coding-Point** [kaustubhgupta/Hacktoberfest#260]
This program is the solution to a very popular question-mase path problem.
the language used *. 
 -
- [x] Java

**Comment by kaustubhgupta** [comment]
Please fill this template properly

**Comment by Coding-Point** [comment]
> Please fill this template properly

@kaustubhgupta how do i fill the template i did not understand . can you please explain .

**Comment by kaustubhgupta** [comment]
Edit the template, replace the placeholder text with your words, don't remove the headings.

**Comment by Coding-Point** [comment]
> Edit the template, replace the placeholder text with your words, don't remove the headings.

@kaustubhgupta does it fine ?
