### ISSUE TITLE
Operations on Array in C

### ISSUE THREAD

**Issue by Gaurisha21** [kaustubhgupta/Hacktoberfest#261]
Operations on Array includes Traversing, Insertion, Searching, Deletion and Sorting.

**Language**

-   [ ] Python
-   [ ] Java
-   [x] C
-   [ ] C++

**Comment by kaustubhgupta** [comment]
@Gaurisha21 you will make this program menu driven?

**Comment by Gaurisha21** [comment]
Yes I can do that.

**Comment by kaustubhgupta** [comment]
Okay assigned to you @Gaurisha21 .
Implement these things also,
- Take input for size of array and array elements
- and then ask for operation to be performed

**Comment by Gaurisha21** [comment]
Okay
Thank you so much.

**Comment by chAlekhya** [comment]
@kaustubhgupta can you please assign me to do in Java

**Comment by Gaurisha21** [comment]
@kaustubhgupta I am getting a Red Cross on my Pull Request. I am new to this, so kindly tell the error and the reason for it. ANd also how to resolve this.

**Comment by neha07kumari** [comment]
can i do it in python @kaustubhgupta

**Comment by rgarg-2711** [comment]
can you please assign it to me?

**Comment by kaustubhgupta** [comment]
This issue was assigned and only tagged as C for a purpose. Please refrain from commenting on the assigned issue to be assigned to you

**Comment by rishika-singh49** [comment]
I would like to work on this.....
will you please assign me this issue in c ?

**Comment by kaustubhgupta** [comment]
> This issue was assigned and only tagged as C for a purpose. Please refrain from commenting on the assigned issue to be assigned to you

@rishika-singh49

**Comment by prakhar-agarwall** [comment]
I'd like to take up this issue in C++ or Python
