### ISSUE TITLE
Tic-Tac-Toe Game in Python language

### ISSUE THREAD

**Issue by arpitsomani8** [kaustubhgupta/Hacktoberfest#262]
Tic-Tac-Toe Game in Python language

This is a console based two player game, entirely written in python language.

**Languages**

-   [ ] Python

**Comment by kaustubhgupta** [comment]
@arpitsomani8 assigned

**Comment by neha07kumari** [comment]
can i do it in python @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@neha07kumari It's already being done in Python
