### ISSUE TITLE
Virtual Assistant JARVIS for desktop using Python 

### ISSUE THREAD

**Issue by chhipashubham970** [kaustubhgupta/Hacktoberfest#263]
I want to add a virtual assistant in python which does your work like playing music, sending mail, etc by itself just like JARVIS.

**Is your feature request related to a problem? Please describe.**
This is no problem but a project related to virtual assistant for the desktop in python.

**Describe the solution you'd like**
The virtual assistant will listen to your command and analyze that command and work accordingly.

**Additional context**

**Languages**

-   [x] Python

If you like this idea please assign this to me so I can contribute to HacktobeFestr  2020.

**Comment by kaustubhgupta** [comment]
@chhipashubham970 Please bring back the whole issue template and then fill it according to your issue

**Comment by chhipashubham970** [comment]
I have to create a new issue.

**Comment by chhipashubham970** [comment]
@kaustubhgupta I have edited the issue. Please have a look and assign this to me.

**Comment by kaustubhgupta** [comment]
@chhipashubham970 Assigned to you. Do the following things too:
- Add GIF showing the working of the assistant
- Branch of the forked repo ( do not make changes in the master branch)
- Readme update of Python folder

**Comment by kaustubhgupta** [comment]
@chhipashubham970 Are you working on this?

**Comment by chhipashubham970** [comment]
Yes, I am currently working on it.
