### ISSUE TITLE
Minimum spanning tree algorithms - Prim's and Kruskal's

### ISSUE THREAD

**Issue by ManasUniyal** [kaustubhgupta/Hacktoberfest#265]
Minimum spanning tree algorithms - Prim's and Kruskal's

**Describe the solution you'd like**
A minimum spanning tree (MST) or minimum weight spanning tree is a subset of the edges of a connected, edge-weighted un-directed graph that connects all the vertices together, without any cycles and with the minimum possible total edge weight.
There are two greedy algorithms - Prim's and Kruskal's to solve this problem.

**Additional context**
Minimum spanning trees have direct applications in the design of networks, including computer networks, telecommunications networks, transportation networks, water supply networks, and electrical grids.

**Languages**

-   [ ] Python : ?
-   [x] Java : @theDeepanshuMourya
-   [x] C : @rgarg-2711
-   [x] C++: @ManasUniyal

**Comment by kaustubhgupta** [comment]
@ManasUniyal Assigned.

**Comment by theDeepanshuMourya** [comment]
I want to contribute to this for Java Project @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@rgarg-2711 Assigned

**Comment by kaustubhgupta** [comment]
@rgarg-2711 This is already taken up in c++. You can only choose C or Python

**Comment by rgarg-2711** [comment]
can I choose it for C?

**Comment by kaustubhgupta** [comment]
@rgarg-2711 okay assigned to you in C
