### ISSUE TITLE
Add Kotlin Language.

### ISSUE THREAD

**Issue by musaabshirgar1** [kaustubhgupta/Hacktoberfest#266]
Please include a small description or summary of the issue here.

**Is your feature request related to a problem? Please describe.**
It would be amazing if you allow contributors to add code in Kotlin Language as it is becoming popular everyday.

**Comment by kaustubhgupta** [comment]
@musaabshirgar1 I don't have any knowledge of Kotlin and neither I want to take the load for more languages. Thanks for the suggestion though!
