### ISSUE TITLE
Hacktoberfest Repos!

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#27]
# Description

Create a script to grab all the repositories which are tagged as hacktobefest and store their names with URLs in a CSV file. 

# Languages:
- Python 

# Resource:
https://github.com/topics/hacktoberfest

**Comment by abhpd** [comment]
@kaustubhgupta I would love to work on this 😃

**Comment by kaustubhgupta** [comment]
@abhpd assigned! make sure to follow the contribution guidelines

**Comment by abhpd** [comment]
> @abhpd assigned! make sure to follow the contribution guidelines 

Sure 😊 thanks
