### ISSUE TITLE
Prefix to Postfix and Infix in C++

### ISSUE THREAD

**Issue by C0DINGLE** [kaustubhgupta/Hacktoberfest#274]
A converter that takes a prefix expression as user input and outputs the postfix and infix expressions of the same.

**Is your feature request related to a problem? Please describe.**
Its not a problem, but this is part of the data structure and algo course in several colleges and I believe it'll be helpful to several students.

**Describe the solution you'd like**
The gist of the solution is to create an expression tree from the input and parse it in Inorder and Postorder to produce the outputs. The data structures used would be stackNode, and tree.

**Additional context**

**Languages**

-   [ ] Python: ?
-   [x] Java: @PrakashAditya17
-   [x] C: @LalwaniSurendra
-   [x] C++: @C0DINGLE

**Comment by kaustubhgupta** [comment]
@C0DINGLE Assigned to you. Don't make your changes to your master branch. Create a separate branch for this issue

**Comment by PrakashAditya17** [comment]
I can code this in java, please assign if required.

**Comment by kaustubhgupta** [comment]
@PrakashAditya17 assigned

**Comment by LalwaniSurendra** [comment]
Can I take this in C?

**Comment by PrakashAditya17** [comment]
@kaustubhgupta ,
I have added the code(for PrefixConversion) in Java Folder(in the forked repo). Please check if its valid.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta ,
> I have added the code(for PrefixConversion) in Java Folder(in the forked repo). Please check if its valid.

I cant't see any PR linked with this issue. Please edit your PR template to link it to this issue

**Comment by PrakashAditya17** [comment]
Okay I am editing the PR template.
