### ISSUE TITLE
Quick sort

### ISSUE THREAD

**Issue by DefCon-018** [kaustubhgupta/Hacktoberfest#283]
Like Merge Sort, QuickSort is a Divide and Conquer algorithm. It picks an element as pivot and partitions the given array around the picked pivot

**Is your feature request related to a problem? Please describe.**
It is a sorting algorithm with time complexity O(nlogn)

**Describe the solution you'd like**
I want to sort an array

**Additional context**

**Languages**

-   [x] Python: @rosse 
-   [x] Java: @chAlekhya
-   [x] C: @neha07kumari 
-   [x] C++ : @DefCon-018

**Comment by chAlekhya** [comment]
@kaustubhgupta can you please assign this to me. I can do this in Java.

**Comment by 13snehitha** [comment]
@kaustubhgupta Please assign this to me, I'll do it in python

**Comment by neha07kumari** [comment]
can you assign me this issue . I want to solve it in C. @kaustubhgupta

**Comment by rgarg-2711** [comment]
Can you please assign me it for c++?

**Comment by kaustubhgupta** [comment]
> Can you please assign me it for c++?

Only Python is available

**Comment by rgarg-2711** [comment]
> > Can you please assign me it for c++?
> 
> Only Python is available

I dont know python going to look on other issues.

**Comment by frosse** [comment]
@kaustubhgupta Can you assign me for python implementation?

**Comment by prakhar-agarwall** [comment]
I'd like to take up this issue in Python
