### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by DefCon-018** [kaustubhgupta/Hacktoberfest#287]
Write an efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.

**Is your feature request related to a problem? Please describe.**
It is not a problem. It is an efficient algorithm to find largest subarray in sum in O(n) complexity

**Describe the solution you'd like**
Simple idea of the Kadane’s algorithm is to look for all positive contiguous segments of the array.

**Additional context**

**Languages**

-   [x] Python : @13snehitha
-   [x] Java : @DefCon-018
-   [x] C: @rgarg-2711
-   [x] C++: @Blackwidow2981

**Comment by 13snehitha** [comment]
@kaustubhgupta Can you please allot this to me, i can do it in python.

**Comment by rgarg-2711** [comment]
can you please assign it to me?

**Comment by Blackwidow2981** [comment]
Hi ,
I would love to work on this project  in Java.

**Comment by kaustubhgupta** [comment]
@Blackwidow2981 can you take this up in C++?

**Comment by motabhai-bhagwaan** [comment]
Hi Kaustubh,

Can I work on this in C++, if the issue is still open?

**Comment by Blackwidow2981** [comment]
yes @kaustubhgupta I can take it up in c++

**Comment by LalwaniSurendra** [comment]
Can I take this in Java?

**Comment by sarthak-1503** [comment]
I have added Kadane's Algorithm in C++ programming language. Please review my pull request.

**Comment by sarthak-1503** [comment]
Please review my pull request #359

**Comment by kaustubhgupta** [comment]
> Please review my pull request #359

Your PR was marked invalid as neither you were assigned this issue nor the assignment was needed as all languages are already assigned

**Comment by sarthak-1503** [comment]
Sorry, I am a beginner in open source. Can you please assign it to me now for C++ if it's available?
