### ISSUE TITLE
A simple but yet tricky Car Game coded in Python.

### ISSUE THREAD

**Issue by TechLead-21** [kaustubhgupta/Hacktoberfest#295]
A fun and full of python knowledge basic Car Game for beginners that covers the nested if-else, methods concepts.

**Languages**

-   [x] Python
-   [ ] Java
-   [ ] C
-   [ ] C++

**Comment by kaustubhgupta** [comment]
@TechLead-21 If you have already implemented it somewhere else or you are pushing you repository code then we don't want any duplicate code. But if you will build this from scratch then we can assign this issue

**Comment by TechLead-21** [comment]
> @TechLead-21 If you have already implemented it somewhere else or you are pushing you repository code then we don't want any duplicate code. But if you will build this from scratch then we can assign this issue

_No I haven't implemented it before, I will build it from scratch, and believe me, it will the only one on Github_
