### ISSUE TITLE
I want to add Ternary Search implementation in java

### ISSUE THREAD

**Issue by Priyankarajput1** [kaustubhgupta/Hacktoberfest#302]
Please include a small description or summary of the issue here.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Languages**

-   [ ] Python
-   [x] Java : @Priyankarajput1
-   [ ] C
-   [ ] C++

**Comment by kaustubhgupta** [comment]
@YashSaxena9 Is it worth assigning?

**Comment by YashSaxena9** [comment]
@kaustubhgupta i think it's worth assigning, this task is for first time contributors. :)

**Comment by YashSaxena9** [comment]
@Priyankarajput1 assigned to you, please follow our contribution guide :)
