### ISSUE TITLE
I want to add Java code to illustrate HashSet and HashMap. 

### ISSUE THREAD

**Issue by varad64** [kaustubhgupta/Hacktoberfest#303]
Please include a small description or summary of the issue here.

The code to illustrate HashSet would give an efficient solution to the problem of counting distinct elements in an array.
The code to illustrate HashMap would give an efficient solution to the problem of counting frequencies of elements in an array.

**Describe the solution you'd like**

**Additional context**

**Languages**

-   [ ] Python
-   [x] Java
-   [ ] C
-   [ ] C++

**Comment by kaustubhgupta** [comment]
@varad64 We already have some code related to this

**Comment by varad64** [comment]
I'm sorry about this @kaustubhgupta I actually tried finding the code but couldn't which is why I went for a new issue
