### ISSUE TITLE
Java implementation of Sieve of Eratosthenes to generate prime numbers.

### ISSUE THREAD

**Issue by prateekrai123** [kaustubhgupta/Hacktoberfest#308]
Please include a small description or summary of the issue here.

**Is your feature request related to a problem? Please describe.**
It will help people to understand the implementation Sieve of Eratosthenes to generate prime numbers in O(n*log(log(n))) time complexity.

**Describe the solution you'd like**
A standard implementation of Sieve of Eratosthenes.

**Languages**

-   [ ] Python
-   [x] Java
-   [ ] C
-   [ ] C++

**Comment by prateekrai123** [comment]
Thanks for assigning me.

**Comment by LalwaniSurendra** [comment]
Can you assign this issue to me (for Java)?

**Comment by PrakashAditya17** [comment]
I can code this in Java or C as required.
