### ISSUE TITLE
Why is my PR labelled invalid?

### ISSUE THREAD

**Issue by parinita08** [kaustubhgupta/Hacktoberfest#310]
# Description
My recent pull request of adding shell sort to the Sorting Algorithm folder has been labelled as invalid.

# Additional context
Can I please know why it has been labelled invalid.

# Languages and Assignees:
-   [ x ] Python: @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@parinita08 Have a look at contribution guidelines

**Comment by parinita08** [comment]
@kaustubhgupta okay, thank you.
