### ISSUE TITLE
I want to contribute 5 python programs

### ISSUE THREAD

**Issue by AnOnYmOus001100** [kaustubhgupta/Hacktoberfest#314]
# Description
I want to contribute 5 python programs

# Additional context
triangle_area.py, celsius_to_fahrenheit.py, multiplication_table.py, sum_of_n_numbers.py and check_leap_year.py

# Languages and Assignees:
-   [x] Python: @

**Comment by kaustubhgupta** [comment]
https://github.com/AnOnYmOus001100/Code_Repository/tree/main/Basic%20Python%20Programs

A clear case of spamming other repos with the same code.

**Comment by AnOnYmOus001100** [comment]
Hey that's my own repository, will make it private soon

**Comment by AnOnYmOus001100** [comment]
Ok, Code repository is now private, I am just keeping a copy of my programs to keep track of them. There's no spamming or plagirism, the codes are written by me and executed.

**Comment by kaustubhgupta** [comment]
@AnOnYmOus001100 I have seen the repo, it was not at all a backup repo it was inviting other contributors to make their PR, and that's absolutely fine your account your choice. Even though you have implemented your codes and that's great but you have already pushed them in your repo and I also know this thing you will make it public one day. I can't continue this conversation ahead
