### ISSUE TITLE
Recursive implementation of printing all subsets of a given string in Java

### ISSUE THREAD

**Issue by varad64** [kaustubhgupta/Hacktoberfest#316]
# Description
Hello, I'd like to a recursive implementation of printing all the subsets of an input string using Java.

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @matteomessmer
-   [x] Java: @varad64
-   [x] C: @yashnavgire 
-   [x] C++: @muffpy

**Comment by matteomessmer** [comment]
Can I make this in python?

**Comment by AK271** [comment]
Hi, I would like to work on this issue. Could you please assign it to me.

**Comment by kaustubhgupta** [comment]
@AK271 language ?

**Comment by AK271** [comment]
@kaustubhgupta I will be coding in Java

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I will be coding in Java

Java is already taken by someone

**Comment by muffpy** [comment]
@kaustubhgupta I can do it in C++

**Comment by muffpy** [comment]
@kaustubhgupta there's a merge conflict in the README file for C++ because someone else opened a new PR with their program description in the README. How do we solve this? @kaustubhgupta

**Comment by yashnavgire** [comment]
Hi,I would like to implement this in C,please assign it to me.

**Comment by yashnavgire** [comment]
Added Subset_string C #378
