### ISSUE TITLE
Shell, Bucket and Radix Sort

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#318]
# Description
Implement the following sorting algorithms in one PR:
- Shell Sort
- Bucket Sort
- Radix Sort

# Additional context
Reference can be taken from geek for geeks but it should be implemented by yourself with your own comments

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [x] Python: @Tvashta
-   [x] Java: @AtalKhandelwal 
-   [x] C: @priyalgupta09
-   [x] C++: @alvinuday

**Comment by AtalKhandelwal** [comment]
@kaustubhgupta Please assign it to me I can do it in java

**Comment by varad64** [comment]
> @kaustubhgupta Please assign it to me I can do it in java

@AtalKhandelwal will you be doing all three?
If not please tell me, I'll do the remaining one(s) in Java.

**Comment by kaustubhgupta** [comment]
> > @kaustubhgupta Please assign it to me I can do it in java
> 
> @AtalKhandelwal will you be doing all three?
> If not please tell me, I'll do the remaining one(s) in Java.

Only one person is allowed to work in one language for one issue

**Comment by AtalKhandelwal** [comment]
I can do all three in Java

**Comment by priyalgupta09** [comment]
i can do all three in c please assign me. Thank you.

**Comment by kartikeyaGUPTA45** [comment]
@kaustubhgupta please assign these sorting algorithms to me in C++

**Comment by PrakashAditya17** [comment]
I can do it in Java. Assign me any of the 3 sortings.

**Comment by Tvashta** [comment]
I will be able to do these sorting algorithms in python. Kindly assign these.

**Comment by kartikeyaGUPTA45** [comment]
@kaustubhgupta please assign me the Radix Sort and Bucket Sort

**Comment by kaustubhgupta** [comment]
@kartikeyaGUPTA45 You already made your commits and now you will just make new PR. Therefore I will assign this to someone else

**Comment by SaloniK17** [comment]
please assign me shell sort and radix sort in c language?
Thank you

**Comment by alvinuday** [comment]
Hi i would like to implement shell sort, bucket sort,radix sort in c++ , can you assign it to me
