### ISSUE TITLE
Concept of probability and binomial  theorem

### ISSUE THREAD

**Issue by aastha0326** [kaustubhgupta/Hacktoberfest#331]
# Description
To find the Probability of getting at least K heads in N tosses of Coins

# Important Checklist

[. ] I have read the contribution guidelines before making this issue.
[. ] I have verified this issue program is not already implemented
[ .] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @aastha01chauhan

**Comment by aastha0326** [comment]
Please put the label HACKTOBERFEST and kindly let me work on this.

**Comment by kaustubhgupta** [comment]
@aastha01chauhan Fill the issue template properly

**Comment by aastha0326** [comment]
Hi, I have done the same. Please assign me the task.

**Comment by kaustubhgupta** [comment]
@aastha01chauhan which language?

**Comment by aastha0326** [comment]
Python and java.
Please put the label hacktoberfest

**Comment by kaustubhgupta** [comment]
You can only work in one language for each issue choose one

**Comment by aastha0326** [comment]
Then it is Java. 
Please don't forget to put the label for hacktoberfest.

**Comment by kaustubhgupta** [comment]
@aastha01chauhan Are you working on this?

**Comment by aastha0326** [comment]
Yes. I am. I will complete it by today or latest by tomorrow evening.

**Comment by aastha0326** [comment]
I have done it.
