### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by ivinaypathak** [kaustubhgupta/Hacktoberfest#334]
# Description
- Used to find shortest path from source to every other vertex on the graph.
- Works only for positive weights. Fails for negative weight edges.
- Time Complexity : O(ElogV)

# Additional context
- For more refer : [https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/]()

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] C++:  @ivinaypathak
-   [x] Python: @muffpy
-   [x] C: @neha07kumari

**Comment by neha07kumari** [comment]
Please assign me in C.  @ivinaypathak @kaustubhgupta

**Comment by muffpy** [comment]
I can do this in Python

**Comment by PrakashAditya17** [comment]
I can code it in Java.

**Comment by kaustubhgupta** [comment]
> I can code it in Java.

It's already implemented in Java
