### ISSUE TITLE
Insertion in LinkedList 

### ISSUE THREAD

**Issue by sj538** [kaustubhgupta/Hacktoberfest#340]
# Description
, Linked List is a linear data structure. Unlike arrays, linked list elements are not stored at a contiguous location; the elements are linked using pointers.

# Additional context
Methods to insert a new node in linked list are to be implemented. A node can be added in three ways 
1) At the front of the linked list 
2) After a given node. 
3) At the end of the linked list.

# Important Checklist 
-   [. ] I have read the contribution guidelines before making this issue.
-   [. ] I have verified this issue program is not already implemented
-   [ .] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @chAlekhya 
-   [x] Java: @jindalsachin
-   [x] C: @muffpy 
-   [x] C++: @valar-yudha

**Comment by sj538** [comment]
Please assign me this issue(for Java).

**Comment by muffpy** [comment]
I can do this in C

**Comment by AK271** [comment]
Hi, I would like to work on this in Java

**Comment by deepharshsri** [comment]
Hey can you assign me, I can do this in JAVA?

**Comment by masterdobby** [comment]
hey, can you assign this to me for C++?

**Comment by kaustubhgupta** [comment]
@AK271  @deepharshsri  It's already assigned in Java to someone else

**Comment by deepharshsri** [comment]
Hey,
I request you to make it FCFS?

**Comment by kaustubhgupta** [comment]
Although it's pretty obvious that when I am editing the issue and assigning only one person per language, still  I will make changes in contribution guidelines as it may be creating confusion. Thanks for the suggestion

**Comment by PrakashAditya17** [comment]
I can code this in Java, since its still pending in java (if assigned).

**Comment by chAlekhya** [comment]
Hey @kaustubhgupta, can you assign me this for python?
