### ISSUE TITLE
Print Factorial of a number using stack

### ISSUE THREAD

**Issue by gh4abhi** [kaustubhgupta/Hacktoberfest#343]
# Description
Print Factorial of a number using stack

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [ ] Python: @
-   [x] Java: @13snehitha
-   [x] C: @gh4abhi
-   [x] C++: @NandiniMundra-8

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by 13snehitha** [comment]
@kaustubhgupta 
Can you allot this to me in java

**Comment by NandiniMundra-8** [comment]
hey @kaustubhgupta , I would love to perform this task in c++,so can you assign this to me?

**Comment by sid-1207** [comment]
Hey can you assign this issue to me?
I will solve it in C
