### ISSUE TITLE
merge and quick sort for linked lists

### ISSUE THREAD

**Issue by KhushiGangopadhyay** [kaustubhgupta/Hacktoberfest#344]
Sorting linked lists using merge sort algorithm and quick sort algorithm

# Important Checklist 
-   [ X] I have read the contribution guidelines before making this issue.
-   [ X] I have verified this issue program is not already implemented
-   [X ] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @Blackwidow2981 
-   [x] Java: @Rohit-2602 
-   [x] C: @kaunik07
-   [X] C++: @KhushiGangopadhyay

**Comment by KhushiGangopadhyay** [comment]
@kaustubhgupta can you assign this to me

**Comment by Rohit-2602** [comment]
@kaustubhgupta can i work on this(in java)....
I have a question that for which linkedList(Doubly or Singly) i have to implement

**Comment by Rohit-2602** [comment]
Can i work on it....

**Comment by Rohit-2602** [comment]
@KhushiGangopadhyay @kaustubhgupta can i do this in java??

**Comment by kaunik07** [comment]
I would like to contribute in this , in C language . Please assign it to me @kaustubhgupta

**Comment by ilmiye** [comment]
Can you assing this to me for python?
