### ISSUE TITLE
Reversal of Doubly link list

### ISSUE THREAD

**Issue by Anupam-Panwar** [kaustubhgupta/Hacktoberfest#349]
# Description
I would like to add a program to reverse Doubly link list in c language

# Additional context
Program would perform the reversal operation on the Doubly link list given by the user

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] C:  @Anupam-Panwar
-   [x] Java: @manishita24 c

**Comment by manishita24** [comment]
I would like to add a program to reverse the Doubly link list in java language. Please assign it to me.

**Comment by SaloniK17** [comment]
Can you assign to me for c++?
Thank you

**Comment by maityankan10** [comment]
please assign it to me in c++, newbie in hactoberfest

**Comment by rishika-singh49** [comment]
I would like to work on this ....
can you please assign to me for c/c++?

**Comment by kaustubhgupta** [comment]
@SaloniK17 @maityankan10 @rishika-singh49 Have a look at updated contribution rules. Only one person will work at one issue language and the assignment will be based on FCFS
