### ISSUE TITLE
Merge Sort in C language

### ISSUE THREAD

**Issue by Anupam-Panwar** [kaustubhgupta/Hacktoberfest#350]
# Description
 I would like to implement
1. Merge sort 
 
# Additional context
Above programs will be in C language

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [ ] Python: @
-   [ ] Java: @
-   [x] C: @
-   [ ] C++: @

**Comment by kaustubhgupta** [comment]
Sorting algorithms have their seperate issues for all languages

**Comment by Anupam-Panwar** [comment]
@kaustubhgupta I want to add merge sort in C language in this repo as this repo currently don't have one under C folder and i am sorry for making the heading to this issue ambiguous.
