### ISSUE TITLE
I want to add Hangman game in python language 

### ISSUE THREAD

**Issue by DebugAgrawal** [kaustubhgupta/Hacktoberfest#368]
# Description
I have created a fun and interactive hangman game along with GUI in python.

# Additional context
![Screenshot (403)](https://user-images.githubusercontent.com/64848982/95665187-9b4f3e00-0b6b-11eb-8f1e-1fb8845a2ddf.png)

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @
-   [ ] Java: @
-   [ ] C: @
-   [ ] C++: @

**Comment by kaustubhgupta** [comment]
Please refrain from making duplicate PRs. I found one of your PR here which is exactly the same as this one :
https://github.com/abhpd/hacktoberfest2020/pull/68

This will not be tolerated

**Comment by DebugAgrawal** [comment]
Sorry for this.
When I firstly made PR [abhpd/hacktoberfest2020#68](abhpd/hacktoberfest2020#68) I didn't  knew that [abhpd/hacktoberfest2020](abhpd/hacktoberfest2020#68) repo is not under Hacktoberfest2020
So I contributed here the same
