### ISSUE TITLE
Small game using java

### ISSUE THREAD

**Issue by Anupam-Panwar** [kaustubhgupta/Hacktoberfest#388]
# Description
I would like to add a small game that will perform following tasks
1. Will ask name of the user
2. Will ask number of question from the user
3. If the answer is correct then user will be rewarded

# Additional context
1.This program would be in java language
2. Output of the program will be in proper formatted manner in order to make it appealing to the user

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @Anupam-Panwar

**Comment by kaustubhgupta** [comment]
@Anupam-Panwar Can you make it a GUI application or integrate applet? Not a fancy one just basic

**Comment by Anupam-Panwar** [comment]
@kaustubhgupta It will be a basic game not including GUI 
I will include proper implementation of basic technique to give user a better taste but without GUI

**Comment by kaustubhgupta** [comment]
@Anupam-Panwar okay go for it!
