### ISSUE TITLE
Notify Me 

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#390]
# Description
I make plans for the day but I forget as soon as it's EOD (End of the day)

# Additional context
Write a script that notifies me every four hours about the things I need to do. The things I need to do will be updated in the txt file and the script should read the contents of the file every time it notifies. The notification should be a desktop notification that should run every time I turn on my system and closed on shutdown. It should not consume many resources.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @happyeric77

**Comment by happyeric77** [comment]
@kaustubhgupta Might I help to contribute on it?

**Comment by kaustubhgupta** [comment]
@happyeric77 go ahead! Make sure to read the issue carefully and have a look at contribution guidelines to avoid any PR rejection

**Comment by happyeric77** [comment]
@kaustubhgupta Might I know for which platform's desktop notification you would like it to be:
- [ ] Linux
- [ ] Mac
- [x] Window (windows 10)
