### ISSUE TITLE
PDF tables to Mongo DB

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest#391]
# Description
PDF's have a lot of tables. I need a script to store those tables as Mongo DB.

# Additional context
The script should extract tables from the PDFs, store each table as a separate table in Mongo DB. Create another file that queries this database.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @meghnabhave

**Comment by meghnabhave** [comment]
I would like to contribute to this.

**Comment by kaustubhgupta** [comment]
@meghnabhave Assigned to you!
