### ISSUE TITLE
Program for all permutation of string

### ISSUE THREAD

**Issue by AtalKhandelwal** [kaustubhgupta/Hacktoberfest#401]
# Description
I want to add a program to find all permutation of string in Java.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @chAlekhya 
-   [x] Java: @AtalKhandelwal 
-   [x] C: @alvinuday 
-   [x] C++: @muffpy

**Comment by AtalKhandelwal** [comment]
@kaustubhgupta Please assign it to me in Java.

**Comment by muffpy** [comment]
I can do this in c++

**Comment by chAlekhya** [comment]
@kaustubhgupta please assign it to me in python.

**Comment by Suraj1199** [comment]
I can do it efficiently in any of the assigned languages.

**Comment by alvinuday** [comment]
Hi, i would like to code a program in python to find all permutations of a string , @AtalKhandelwal can you assign it to me for python

**Comment by AtalKhandelwal** [comment]
> Hi, i would like to code a program in python to find all permutations of a string , @AtalKhandelwal can you assign it to me for python

Hi @alvinuday  this issue is already assigned in python. You can ask @kaustubhgupta to assign it to you in C if you can do it in C.

**Comment by alvinuday** [comment]
Hi, i would like to code a program in C to find all permutations of a string , @kaustubhgupta  can you assign it to me for C

**Comment by alvinuday** [comment]
Hi, i would like to code a program in C to find all permutations of a string , @kaustubhgupta can you assign it to me for C

**Comment by muffpy** [comment]
Hi, I can finish this today in C++. Can you please reopen this issue?
