### ISSUE TITLE
2-SAT

### ISSUE THREAD

**Issue by Math-O5** [kaustubhgupta/Hacktoberfest#403]
# Description
The 2-SAT implementation algorithm

# Additional context
The implementation of the NP(Non-Polinominal) problem of satisfaction with two restrictions.

# Important Checklist 
-   [X ] I have read the contribution guidelines before making this issue.
-   [X ] I have verified this issue program is not already implemented
-   [X ] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @Tvashta 
-   [x] Java: @dayushman
-   [ ] C: @
-   [X] C++: @Math-O5

**Comment by Tvashta** [comment]
Could you please assign this to me in the Python category?
-Edit: I am sorry! Kindly assign this to someone else. I will not be able to work on it

**Comment by Math-O5** [comment]
Sorry for the delay, but I was only planning do it only in Oct 27th. I had some tasks to do before. @kaustubhgupta
