### ISSUE TITLE
Music spectrum visualizer with python3.

### ISSUE THREAD

**Issue by JaniniRami** [kaustubhgupta/Hacktoberfest#407]
# Description
A music visualizer that takes audio and plays it live with a visualizer made with python3.

# Additional context
![Untitled](https://user-images.githubusercontent.com/39865850/95961810-3f581400-0e0e-11eb-8096-5ae47d284dde.png)

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @JaniniRami07

**Comment by kaustubhgupta** [comment]
Are you sure so haven't implemented this before?

**Comment by JaniniRami** [comment]
No, I only made a beta version and it has some errors so I kept it private and that screenshot is from the beta version of my program, So I am willing to fix the errors it has, clean the code and contribute my project here!
