### ISSUE TITLE
Add code for Trie Data Structure

### ISSUE THREAD

**Issue by Preetesh21** [kaustubhgupta/Hacktoberfest#411]
# Description
Add code for Trie DataStructure

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @namitamutha 
-   [x] Java: @AK271 
-   [ ] C: @
-   [x] C++: @Preetesh21

**Comment by Preetesh21** [comment]
Can you assign this to me in C++

**Comment by AK271** [comment]
Can you assign this to me in Java

**Comment by namitamutha** [comment]
Can you assign this to me in python?

**Comment by namitamutha** [comment]
#527

**Comment by namitamutha** [comment]
Added Trie implementation in python #527
