### ISSUE TITLE
A-star maze solver algorithm

### ISSUE THREAD

**Issue by Vyvy-vi** [kaustubhgupta/Hacktoberfest#422]
# Description
This is an implementation of the A* algorithm for solving random generated mazes on a webpage
(you guys do take javascript, right?)

# Additional context
Concept discussed here:
https://www.youtube.com/watch?v=W9F8fDQj7Ok

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Javascript
-   [x] html5

**Comment by kaustubhgupta** [comment]
Currently, we don't have any folder for javascript

**Comment by Vyvy-vi** [comment]
Oh. Anyways, Thank You!
