### ISSUE TITLE
Quick Sort 

### ISSUE THREAD

**Issue by donghoon-tech** [kaustubhgupta/Hacktoberfest#431]
# Description
add code for quick sort

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @1031nice
-   [x] C: @Mayshank18

**Comment by donghoon-tech** [comment]
@kaustubhgupta Please assign it to me I can do it in java

**Comment by Mayshank18** [comment]
Please assign this issue to me

**Comment by LaxmiNyamagoud** [comment]
can you assign this work?

**Comment by Anurajeev** [comment]
Can you assign this to me

**Comment by AniketDGiri** [comment]
Could you please assign this to me in C++?

**Comment by kaustubhgupta** [comment]
@LaxmiNyamagoud @AniketDGiri @Anurajeev This issue was only available in C & Python which is assigned

**Comment by AniketDGiri** [comment]
ok
