### ISSUE TITLE
Basic quiz game using Java

### ISSUE THREAD

**Issue by Shreyansu** [kaustubhgupta/Hacktoberfest#444]
# Description
I would like to create a basic quiz game using Java containing a few questions. If the answer is correct, then the user will be awarded points. At last user will be shown a total number of points.

# Additional context
      This would be an android app

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [ ] Python: @
-   [x] Java: @
-   [ ] C: @
-   [ ] C++: @

**Comment by gillesigot** [comment]
Hello, can I do it in Python?

**Comment by kaustubhgupta** [comment]
we are not accepting android apps programs
