### ISSUE TITLE
Sorted Square Array

### ISSUE THREAD

**Issue by alpha037** [kaustubhgupta/Hacktoberfest#459]
# Description
Given an array of integers A sorted in non-decreasing order, return an array of the squares of each number, also in sorted non-decreasing order.

I would like to add the solution to this problem.

# Additional context
Leetcode problem: https://leetcode.com/problems/squares-of-a-sorted-array/

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @

**Comment by kaustubhgupta** [comment]
This problem has multiple solutions so it won't be a valid contribution
