### ISSUE TITLE
Maximum Subarray Sum

### ISSUE THREAD

**Issue by alpha037** [kaustubhgupta/Hacktoberfest#460]
# Description
Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.

I would like to submit a solution to this problem.

# Additional context
Leetcode: https://leetcode.com/problems/maximum-subarray/

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @

**Comment by LautaroLobo12** [comment]
I would love to work on this one :)

**Comment by alpha037** [comment]
Hey, could you work on something else? I already told that I'll submit a solution. 

Thank you :)

**Comment by kaustubhgupta** [comment]
We are not accepting leetcode solutions as they are widely available and there is a high possibility of plagiarised/same/copied solution even though you code from scratch.
