### ISSUE TITLE
Stack and Queue Implementation 

### ISSUE THREAD

**Issue by AtalKhandelwal** [kaustubhgupta/Hacktoberfest#468]
# Description
Implementation Of Stack and Queue data structure.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [ ] Python: @
-   [ ] Java: @
-   [ ] C: @
-   [ ] C++: @

**Comment by AtalKhandelwal** [comment]
@kaustubhgupta  Please assign it to me in Java

**Comment by neha07kumari** [comment]
Please assign me the stack implementation in C. @AtalKhandelwal  @kaustubhgupta

**Comment by kaustubhgupta** [comment]
We will think of a better way to quote this question as assigning it normally would not be beneficial
