### ISSUE TITLE
Convert Fahrenheit to Celsius C++ Code

### ISSUE THREAD

**Issue by shubhamsingla807** [kaustubhgupta/Hacktoberfest#470]
# Description
This code will convert Fahrenheit temperature to Celsius Code

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @Addhyay
-   [x] Java: @AK271 
-   [x] C: @saitaruns 
-   [x] C++: @shubhamsingla807

**Comment by AK271** [comment]
Could you please assign this to me in Java

**Comment by kaustubhgupta** [comment]
@shubhamsingla807 @AK271 Assigned to you

**Comment by addhyay** [comment]
Could you please assign this to me in Python?

**Comment by saitaruns** [comment]
Could you please assign this to me in C? @kaustubhgupta
