### ISSUE TITLE
Multiplicative Inverse using Extended Euclidean Algorithm

### ISSUE THREAD

**Issue by addhyay** [kaustubhgupta/Hacktoberfest#474]
# Description
This will output Multiplicative Inverse of a number let say **p** on plane **Zq**. Here the main function of code will accept **p** and **q** and input.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @Addhyay 
-   [x] Java: @ewei068 
-   [ ] C: @
-   [ ] C++: @

**Comment by kaustubhgupta** [comment]
@Addhyay Which language would you prefer? You can choose only one

**Comment by addhyay** [comment]
@kaustubhgupta  I'll do it in python

**Comment by ewei068** [comment]
@kaustubhgupta I can do this in Java
