### ISSUE TITLE
Discord bot to send messages in any server/channel

### ISSUE THREAD

**Issue by pedrosv20** [kaustubhgupta/Hacktoberfest#483]
# Description
Create a bot to send messages every single x seconds in any server and channel in discord you want
you have to pass email and password, the server name, channel name, is_nsfw flag, time between messages and the array of messages.

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @pedrosv20

**Comment by kaustubhgupta** [comment]
@pedrosv20 Hey! I have assigned you all the issues requested. Do follow contribution guidelines to avoid any rejections!
