### ISSUE TITLE
Evaluating a Postfix Expression using Stack in C Language

### ISSUE THREAD

**Issue by Debargha-arch** [kaustubhgupta/Hacktoberfest#490]
# Description
I have created a program which on inputting a particular postfix expression would return its evaluated form. I have used the Stack Data Structure to implement it.

# Additional context
Add any other context, links references, or screenshots about the feature request here.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [ ] Python: @
-   [x] Java: @namitamutha 
-   [x] C: @Debargha-arch 
-   [x] C++: @beertocode

**Comment by namitamutha** [comment]
Assign this to me in java @kaustubhgupta

**Comment by beertocode** [comment]
Assign me in C++.

**Comment by joeljsv** [comment]
assign me in c

**Comment by kaustubhgupta** [comment]
@joeljsv This is already assigned in C. Also, do not make PR until you are not assigned any issue. All this is mentioned in contribution guidelines

**Comment by joeljsv** [comment]
> @joeljsv This is already assigned in C. Also, do not make PR until you are not assigned any issue. All this is mentioned in contribution guidelines 

Can you assign me?
