### ISSUE TITLE
I wish to contribute to this with the code of Insertion Sort in Python

### ISSUE THREAD

**Issue by divyxnsh** [kaustubhgupta/Hacktoberfest#506]
# Description
(Replace this text holder with your description: Please include a small description or summary of the issue here )

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [ ] I have read the contribution guidelines before making this issue.
-   [ ] I have verified this issue program is not already implemented
-   [ ] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [ ] Python: @
-   [ ] Java: @
-   [ ] C: @
-   [ ] C++: @

**Comment by kaustubhgupta** [comment]
https://github.com/kaustubhgupta/Hacktoberfest2020_/blob/master/Python/Sorting_Algorithms/insertion_sort.py
It's already implemented
