### ISSUE TITLE
All possible substrings by given number of characters

### ISSUE THREAD

**Issue by rupeshkumar22** [kaustubhgupta/Hacktoberfest#519]
# Description
Two functions with time complexity O(n)
'getallsubstrings(String s)' - return type is string array
'getallsubstringsbynumbers(int n,String s)' - return type is string array

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [ ] Python: @
-   [x] Java: @rupesh-kumar-lpu
-   [ ] C: @
-   [ ] C++: @

**Comment by rupeshkumar22** [comment]
Please assign @kaustubhgupta

**Comment by kaustubhgupta** [comment]
https://github.com/kaustubhgupta/Hacktoberfest2020_/blob/master/Java/SubsetsOfAString.java

isn't this similar to your question?

**Comment by rupeshkumar22** [comment]
@kaustubhgupta Functionality is the same so I don't think there is a need to assign, You may close the issue :) or can I?
