### ISSUE TITLE
Counting sort algo 

### ISSUE THREAD

**Issue by dishantvyas15** [kaustubhgupta/Hacktoberfest#522]
# Description
Hello! I want to contribute to this repo by adding a counting sort algorithm in C++.

# Additional context
-- Not required --

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @namitamutha 
-   [x] C++: @dishantvyas15

**Comment by namitamutha** [comment]
@kaustubhgupta, assign this to me in java

**Comment by dishantvyas15** [comment]
@kaustubhgupta I've made a pull request (#530) that potentially fixes this issue.
Review requested.

**Comment by namitamutha** [comment]
@kaustubhgupta, you have assigned me counting sort for java, but have closed the issue
