### ISSUE TITLE
Finding the Minimum number of Swaps to Sort an Array

### ISSUE THREAD

**Issue by dayushman** [kaustubhgupta/Hacktoberfest#536]
# Description
This program finds out the Minimum Number of Swaps that are required to Sort a given Array with O(nlogn) time complexity.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [ ] Python: @
-   [x] Java: @dayushman 
-   [x] C: @himanshuagrl
-   [x] C++: @SymbolofMoon

**Comment by dayushman** [comment]
@kaustubhgupta Please assign me this.

**Comment by joeljsv** [comment]
@kaustubhgupta assign me on **Python**

**Comment by SymbolofMoon** [comment]
@kaustubhgupta  please assign it to me for C++

**Comment by himanshuagarwl** [comment]
@kaustubhgupta please assign me it to me for C++

**Comment by kaustubhgupta** [comment]
@joeljsv Made the same mistake here that's why you will not be allowed to make PRs here.

**Comment by kaustubhgupta** [comment]
@himanshuagrl This was already requested in C++ by another person. Now you can only work in C or Python. Make sure you tell your choice before anyone else claim it before you

**Comment by himanshuagarwl** [comment]
@kaustubhgupta ok please assign it to me for C

**Comment by RachanaKampli** [comment]
@kaustubhgupta  Can you assign this to me for python?
