### ISSUE TITLE
Counting Sort for Python 

### ISSUE THREAD

**Issue by rupeshkumar22** [kaustubhgupta/Hacktoberfest#549]
# Description
Counting Sort

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Python: @rupesh-kumar-lpu

**Comment by kaustubhgupta** [comment]
You can only contribute is one language and you are assigned in Python now

**Comment by rupeshkumar22** [comment]
okay Thanks
