### ISSUE TITLE
Juggling Algorithm 

### ISSUE THREAD

**Issue by prateekrai123** [kaustubhgupta/Hacktoberfest#566]
# Description
The algorithm is used to perform Array rotation in O(n) time.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @prateekrai123

**Comment by anirudhps10** [comment]
Can you assign me for python?
