### ISSUE TITLE
Binary Tree Implementation with traversals in Java

### ISSUE THREAD

**Issue by prateekrai123** [kaustubhgupta/Hacktoberfest#567]
# Description
The program will contain the binary tree implementation with inOrder, preOrder and postOrder traversals in Java.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @prateekrai123

**Comment by rupeshkumar22** [comment]
Assign me for Python @kaustubhgupta

**Comment by rupeshkumar22** [comment]
I have checked its not already implemented

**Comment by rupeshkumar22** [comment]
I close the pull request. I just checked that it's already implemented in python as BST_implemetation.py @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@rupesh-kumar-lpu Okay that's good you checked it, you can create more issues if you still want to contribute while being in hacktober fest

**Comment by mansim3006** [comment]
can I Implement this in java?
