### ISSUE TITLE
CombSort in java

### ISSUE THREAD

**Issue by rupeshkumar22** [kaustubhgupta/Hacktoberfest#578]
# Description
I would like to implement comb sort algorithm. Please assign it to me. @kaustubhgupta 

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented
-   [x] I have not pushed this code anywhere else (even my repo)

# Languages and Assignees:
-   [x] Java: @rupesh-kumar-lpu 
-   [x] C++: @AtalKhandelwal

**Comment by AtalKhandelwal** [comment]
Hi @kaustubhgupta Please assign it to me in C++.
