### ISSUE TITLE
Word guessing game

### ISSUE THREAD

**Issue by kjvjobin** [kaustubhgupta/Hacktoberfest#72]
# Word guessing game

Can you please assign me to add a word guessing game

**Comment by YashSaxena9** [comment]
Explain the functionality

**Comment by kjvjobin** [comment]
In this game, the gamer is asked to guess letters, the correct letters are
placed at the proper while the wrong once will give you the next chance to
guess. The best part is we can add as many words as we want in the
dictionary.

Kind Regards,
Keecheril Jobin Varghese
Ph. +91 9673561508

**Comment by kaustubhgupta** [comment]
@jobinkeecheril sounds interesting. Assigned to you!

**Comment by kjvjobin** [comment]
Thank you so much! I'm on it straight away

**Comment by kjvjobin** [comment]
Can I start again? Please assign me again so that I can add my game

**Comment by YashSaxena9** [comment]
Assigned :)
