### ISSUE TITLE
Palindromic Substrings

### ISSUE THREAD

**Issue by YashSaxena9** [kaustubhgupta/Hacktoberfest#73]
**This issue is open for C Implementation**
Palindromic substrings

Make a program to find all possible continuous subsequences of an array and print the ones which are a palindrome.

## Bug Reports
Please replace this line with a brief summary of your issue AND if reporting a build issue include the link.

- [ ] Didn't run?
- [ ] Permission Issues?
- [ ] Broken Links
- [ ] Other Issues? (Add Here)

## Any links, resources or references to solve the issue?
- [ ] Yes

If yes, please the resources in the following format:
- Resource 1
- Resource 2

- [ ] No

**Comment by keerti2001** [comment]
Hey! Can you assign me this

**Comment by kaustubhgupta** [comment]
@keerti2001 assigned to you! Follow contribution guidelines

**Comment by kaustubhgupta** [comment]
@keerti2001 can you specify in which language you will contribute?

**Comment by keerti2001** [comment]
C++

**Comment by kaustubhgupta** [comment]
okay go ahead!

**Comment by YashSaxena9** [comment]
implementation in Java and python still required

**Comment by deVedant** [comment]
> implementation in Java and python still required

I can do it in Python.

**Comment by kaustubhgupta** [comment]
@deVedant assigned to you in python

**Comment by YashSaxena9** [comment]
implementation in java still required

**Comment by khushbu014** [comment]
Can you assign java for me ?

**Comment by YashSaxena9** [comment]
@khushbu014 task assigned to you, happy coding :)

**Comment by sbhavya18** [comment]
kindly assign this task to me. I will be implementing this in c++

**Comment by YashSaxena9** [comment]
@sbhavya18 The task is already completed in C++

**Comment by deVedant** [comment]
I can do it Python.

**Comment by kaustubhgupta** [comment]
This issue is open for C Implementation

**Comment by Tanmay244** [comment]
@kaustubhgupta can you please assign this task to me. I want to implement it using python

**Comment by kaustubhgupta** [comment]
@Tanmay244 actually due to some confusion this issue was already done in Python. Now, this is available in C only. If you're comfortable with C then I can assign this to you
