### ISSUE TITLE
Doubly linked list

### ISSUE THREAD

**Issue by YashSaxena9** [kaustubhgupta/Hacktoberfest#76]
# Doubly linked-list

Implement a general-purpose doubly linked list with proper documentation and all basic methods stated as under.

- [x] Uses templates/generics or anything equivalent for the language used
- [x] Add element
- [x] delete element
- [x] find element
- [x] length of list
- [x] middle of list
- [x] reverse of list

**Comment by sanuj96** [comment]
Please assign this to me

**Comment by sanuj96** [comment]
I would like to contribute in this

**Comment by kaustubhgupta** [comment]
which language? @sanuj96

**Comment by sanuj96** [comment]
c++ @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@sanuj96 assigned!

**Comment by AlecsFerra** [comment]
I will do it in java

**Comment by kaustubhgupta** [comment]
@AlecsFerra Assigned to you in Java

**Comment by Shivansh187** [comment]
I would like to contribute the following in C language @kaustubhgupta

**Comment by YashSaxena9** [comment]
@Shivansh187 go for it, please follow the contribution guide. :)

**Comment by kaustubhgupta** [comment]
@AlecsFerra only your entry left for Java, just a reminder

**Comment by codewdhruv** [comment]
Is this still open for C++? @kaustubhgupta @sanuj96

**Comment by kaustubhgupta** [comment]
nope, c++ is implemented.

**Comment by kaustubhgupta** [comment]
This issue is up for Java

**Comment by shahhardik4599** [comment]
I  would like to contribute the following in Java language @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@shahhardik4599 assigned! make sure to have a look at pinned issues to avoid any PR rejection!
