### ISSUE TITLE
Binary Search Tree implementation

### ISSUE THREAD

**Issue by YashSaxena9** [kaustubhgupta/Hacktoberfest#77]
# Binary Search Tree

Implement a Binary Search Tree with all basic methods like traversals, update, deletion, addition, and finding of data.

# Assignees:

- C: @Harshalszz
- C++: @keerti2001
- Python:
- Java

**Comment by keerti2001** [comment]
Hey ! Can u assign me this task

**Comment by YashSaxena9** [comment]
Task assigned

**Comment by YashSaxena9** [comment]
Implementation in Java, C, and Python are left. Interested people can comment to get the issue assigned!

**Comment by Harshalszz** [comment]
Hey! can I work on this.

**Comment by kaustubhgupta** [comment]
@Harshalszz language?

**Comment by Harshalszz** [comment]
C++

**Comment by Harshalszz** [comment]
C language

**Comment by kaustubhgupta** [comment]
@Harshalszz assigned. Kindly have a look at pinned issues to avoid your PR being rejected

**Comment by kaustubhgupta** [comment]
Issue available in  Java and Python implementation

**Comment by Harshalszz** [comment]
Hey ! can I work on this in python.

**Comment by kaustubhgupta** [comment]
> Hey ! can I work on this in python.

You have already summited your C code. You can contribute to other issues if you want

**Comment by Obnoxious-coder** [comment]
Can u assign me this task for python

**Comment by kaustubhgupta** [comment]
@Obnoxious-coder  assigned. Kindly have a look at pinned issues to avoid your PR being rejected

**Comment by vnishchay** [comment]
I want to work on it
