### ISSUE TITLE
Directory Handler

### ISSUE THREAD

**Issue by YashSaxena9** [kaustubhgupta/Hacktoberfest#78]
**Issue available in C, C++ and Python implementation**

# Directory Handler

- Implement a system that takes two file paths and copies all the files and directories and their content from the first path and duplicates them in the second path.
- use file handling

## Bug Reports
Please replace this line with a brief summary of your issue AND if reporting a build issue include the link.

- [ ] Didn't run?
- [ ] Permission Issues?
- [ ] Broken Links
- [ ] Other Issues? (Add Here)

## Any links, resources, or references to solve the issue?
- [ ] Yes

If yes, please the resources in the following format:
- Resource 1
- Resource 2

- [ ] No

**Comment by khushbu014** [comment]
Can you assign this to me ?

**Comment by YashSaxena9** [comment]
@khushbu014  can you specify in which language you will contribute?

**Comment by deril2605** [comment]
Hi, I am willing to take this up. Preferred language: Python

**Comment by khushbu014** [comment]
I will code in python.

**Comment by CuriousMonkey7** [comment]
Hey @kaustubhgupta ,
I like to contribute to this issue. I will implement this system in java and in python also if needed with good documentation. As you asked it will take file path of both as input/or you can give them in code as well then copy all content of file/directory 1 to second path file.

**Comment by kaustubhgupta** [comment]
Assigness: 
@khushbu014 : Python
@100RABHpy : Java
You can start your work 

@deril2605 can you contribute in C++ as Python was asked before you?

**Comment by kaustubhgupta** [comment]
@khushbu014 are you still working on this?

**Comment by kaustubhgupta** [comment]
This issue is closed
