### ISSUE TITLE
Fast IO for Java

### ISSUE THREAD

**Issue by YashSaxena9** [kaustubhgupta/Hacktoberfest#91]
# Fast IO for Java

Implement classes for fast input and output in java using only raw input reader, streams, and writers.

:warning: **Use of Scanner class prohibited**

Requires
- [x] proper documentation
- [x] Easy to understand logic
- [x] Good space and time complexity
- [x] Less code redundancy
- [x] No plagiarism

**Comment by ghost** [comment]
I would like to contribute in this

**Comment by kaustubhgupta** [comment]
@ransbachm assigned
