### ISSUE TITLE
Addition of Important Graph Algorithms implemented in C++

### ISSUE THREAD

**Issue by Jappan07** [kaustubhgupta/Hacktoberfest#94]
This is to include some of the most important graph algorithms implemented using C++.
If it's fine with you I can creatw a PR so that you can merge it to the project. 
Thank You!

**Comment by kaustubhgupta** [comment]
@Jappan07 can you give some more details about which algorithms you want to implement?

**Comment by Jappan07** [comment]
Like We can add bfs,dfs traversal, SSS, cycle detection, Dijkstra, Prim's, Kahn's Algo

**Comment by kaustubhgupta** [comment]
@Jappan07 add BFS and DFS only, assigned to you. Make sure to follow guidelines and update the language readme with your entry

**Comment by Jappan07** [comment]
Thank you for assigning me the task. I'm on it.👍🏻

**Comment by Jappan07** [comment]
I am having some problem creating the pull request.
Its showing this error message. Please help me.
<img width="929" alt="Screen Shot 2020-10-03 at 2 55 34 PM" src="https://user-images.githubusercontent.com/42716542/94988112-96e1be80-0588-11eb-8f5a-bbc671bdf659.png">
