### ISSUE TITLE
Simple API with NodeJS

### ISSUE THREAD

**Issue by l4ur4oliveira** [kaustubhgupta/Hacktoberfest#98]
# Simple API with NodeJS

A simple API to exercise the basic HTTP verbs (GET, POST, PUT and DELETE) using Express.

**Comment by l4ur4oliveira** [comment]
I would like to work on it! :)

**Comment by kaustubhgupta** [comment]
@YashSaxena9 should we assign this issue?

**Comment by YashSaxena9** [comment]
Task assigned, go for it !
Please follow the contribution guide and have proper documentation for your code functionality. :)
